# https://golangci-lint.run/usage/configuration/#config-file
output:
  sort-results: true
  formats:
    - format: colored-line-number
run:
  timeout: 10m
  tests: true
  allow-parallel-runners: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - "tmp"
linters:
  enable-all: true
  disable:
    - copyloopvar
    - cyclop
    - deadcode
    - depguard
    - dupl
    - exhaustivestruct
    - exhaustruct
    - gocognit
    - golint
    - ifshort
    - interfacer
    - intrange
    - maligned
    - nestif
    - nlreturn
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - wsl
linters-settings:
  goimports:
    local-prefixes: github.com/ilaif/athena-cycle
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/ilaif/athena-cycle)
    custom-order: true
    skip-generated: false
  funlen:
    lines: -1
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 5
  lll:
    line-length: 150
  wrapcheck:
    ignorePackageGlobs:
      - "github.com/ilaif/athena-cycle/**"
  gocyclo:
    min-complexity: 20
  varnamelen:
    max-distance: 50
    ignore-names: [db]
  cyclop:
    max-complexity: 15
