version: '3.8'
services:
  db:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8000:80"
      # - "443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
volumes:
  db:
    driver: local
