apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncer
  template:
    metadata:
      labels:
        app: syncer
    spec:
      containers:
        - name: syncer
          image: ifallach/athena-cycle-syncer:main
          imagePullPolicy: Always
          env:
            # TODO: update this
            - name: GITHUB_REPOSITORIES
              value: "org/repo-name" # Replace with your repository names
            - name: GITHUB_TOKENS
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: GITHUB_TOKEN
            - name: DB_POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-uri
                  key: POSTGRES_URI
            # - name: JIRA_PROJECTS
            #   value: '["CDE"]'
            # - name: JIRA_SITE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: jira-secret
            #       key: JIRA_SITE_URL
            # - name: JIRA_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: jira-secret
            #       key: JIRA_USERNAME
            # - name: JIRA_API_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: jira-secret
            #       key: JIRA_API_TOKEN
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
