name: syncer-checks
on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with: { go-version: 1.21.6 }
      - run: go mod tidy
        working-directory: ./go-syncer
      - run: make lint
        working-directory: ./go-syncer
