name: syncer-checks
on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with: { go-version: 1.21.6 }
      - run: go mod tidy
        working-directory: ./go-syncer
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: "v1.57.2"
          working-directory: ./go-syncer
